### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by sql-aus-hh**
Google has changed the UI and the screenshots weren't correct anymore and the step "Creating service Account" was misleading as there is no more link in the listing/description
I took new screenshots and uploaded them for better understanding and following the jumpstart.

### CODE REVIEW

**Review by dkirby-ms — CHANGES_REQUESTED** [review]
Thank you for your PR. We would like to keep the screenshot file names aligned as they currently are, so before we can merge this can you please change the location and name of the files to match the current state? 

For example, include the updated screenshots as part of the PR and keep the same filename.

**Comment by dkirby-ms** [comment]
Hi @sql-aus-hh, thank you for your PR. 

Please align screenshots with current file naming syntax (e.g. 06.png) and include the actual screens with the PR instead of linking from github user-images.

**Comment by sql-aus-hh** [comment]
Hi @dkirby-ms ,

there was a discussion during MVP Summit on "submitting images to MSFT Github" and the outcome was to include the new images with "external" images...

Now I put them directly into the docs/img folder
Please check.

**Review by dkirby-ms — APPROVED** [review]
Thank you

**Pull request merged**
