### PR TITLE
Add Hypermarket GItOps Config

### PR DESCRIPTION
**Pull request by mrhoads**
This should add the GitOps configuration for contoso-hypermarket.  The CLI equivalent is:

```
az k8s-configuration flux create --cluster-name <cluster>  --resource-group <resource group> --name contoso-hypermarket --namespace default --cluster-type connectedClusters --scope cluster --url https://github.com/Azure/jumpstart-apps --branch main --kustomization name=contoso-hypermarket path=./agora/contoso_hypermarket/

```

### CODE REVIEW

**Review by dkirby-ms — APPROVED** [review]

**Comment by dkirby-ms** [comment]
There is a merge conflict here @mrhoads

**Review by dkirby-ms — CHANGES_REQUESTED** [review]
fix merge conflicts

**Review by fcabrera23 — APPROVED** [review]
LGTM

**Comment by mrhoads** [comment]
merge conflict should be resolved but hoping fresh eyes can look at this before doing the merge

**Review by sebassem — CHANGES_REQUESTED** [review]
LGTM - Just call it out in the logonscript to execute

**Review by dkirby-ms — APPROVED** [review]

**Pull request merged**
