### PR TITLE
added Bicep file

### PR DESCRIPTION
**Pull request by daveRendon**

### CODE REVIEW

**Comment by lanicolas** [comment]
Hi @daveRendon 

Thank you very much for your contribution and taking the time to adding this scenario to the Jumpstart! To be able to publish this we should accompany it by a readme file that shows people how to use it so this is a great opportunity to have a dedicated scenario similar to this one: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/azure_arm_template_win/ but specifically for bicep. Would you be open to write the usage guide?

**Comment by daveRendon** [comment]
Hi @lanicolas, thanks much for the quick response, since the Bicep file creates the ARM template, not sure if it makes sense to duplicate the same content. I'm happy to write the usage guide, however, it will be pretty similar to the existing document you referred to. Could you please let me know your thoughts?

**Comment by lanicolas** [comment]
Hi @daveRendon I agree it will be very similar to the ARM template one, however since have scenarios per automation, like Terraform or ARM, we do feel this is a relevant scenario to have its own dedicated section, even if the step by step does not change that much. So this just means that most of the write up is done we would have just to adapt some commands and instructions. Makes sense?

**Comment by lanicolas** [comment]
Awesome @daveRendon feel free to use the ARM template one as a starting point to make it easier https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/azure_arm_template_win/ and for additional reference you have these  scenario guidelines: https://azurearcjumpstart.io/scenario_guidelines, let me know if I can assist

**Comment by lanicolas** [comment]
hi @daveRendon wanted to ping you and see how you were doing with the scenario, please if you need any help or have any questions let me know.

**Comment by lanicolas** [comment]
hi @daveRendon just asking how is it going and checking if you are still interested in building the scenario

**Comment by likamrat** [comment]
Hey @daveRendon, 
As @lanicolas mentioned, since this is not a complete Jumpstart scenario, we will be closing this PR for now. We will consider creating this scenario in future sprints. 
Feel free to comment on this PR and thank you for your willingness to contribute to the Jumpstart!

**Pull request closed without merging**
