### PR TITLE
Remove CAPI Scenarios

### PR DESCRIPTION
**Pull request by zaidmohd**
Remove CAPI scenarios from
- azure_arc_app_services_jumpstart
- azure_arc_data_jumpstart
- azure_arc_k8s_jumpstart

Remove azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1 from ArcBox

### CODE REVIEW

**Review by janegilring — APPROVED** [review]
LGTM

**Review by chintalavr — APPROVED** [review]
Everything looks good, all capi references are being removed.

**Review by dkirby-ms — APPROVED** [review]
LGTM, looks like removed files only.

**Comment by zaidmohd** [comment]
Will open a new PR

**Pull request closed without merging**
