### PR TITLE
Calico folder structure

### PR DESCRIPTION
**Pull request by lanicolas**
Refreshed Calico scenarios to align folder structure

### CODE REVIEW

**Review by likamrat — CHANGES_REQUESTED** [review]
The multi-distro path is there by design. this scenario is relevant for EKS/GKE as mentioned in the beginning, that is the reason why.

**Comment by lanicolas** [comment]
> The multi-distro path is there by design. this scenario is relevant for EKS/GKE as mentioned in the beginning, that is the reason why.

not sure what you mean, I did not remove the multi-distro path, the _index.md and screenshots are there too. As for the automations I did not create a folder to follow the same structure we have for servers where we don't have an specific section for day2 for example all of them are on a flat directory. Should I add one for the automations?

**Comment by lanicolas** [comment]
added multi_distributions folder

**Review by likamrat — APPROVED** [review]
LGTM

**Pull request merged**
